spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  
    show-sql: false
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
 pathsToMatch: /api/**/v1/**
 swagger-ui:
  use-root-path: true